apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: dot-net-auto-instrumentation
  namespace: default
spec:
  exporter:
    endpoint: http://traces-collector-collector:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"