apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dotnet-app-helm
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dotnet-app
  endpoints:
  - port: http
    interval: 15s
    path: /metrics